baseURL = 'https://america.github.io/'
languageCode = 'ja'
title = '雑記'
theme = "PaperMod"

[pagination]
  pagerSize = 10


[params]
  # 一部PaperMod固有の設定
  defaultTheme = "auto" # ダーク/ライトテーマの自動切り替え
  showReadingTime = true # 記事の読み時間を表示
  disableSpecial1st = false # 特殊な1記事目デザインを無効化
  enableGitInfo = true # 更新日時を表示
  mainSections = ["post"]  # ホームに並べるセクション
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  # ホーム上部の紹介
  [params.homeInfoParams]
    Title = "雑記"
    Content = "Linux / Arch / Waydroid などのメモ。備忘録でも、誰かの助けになりますように。"

  [params.assets]
  favicon = "/images/favicon.png"
  apple_touch_icon = "/images/apple-touch-icon.png"

  # 抜粋の長さ（トップの要約）
  summaryLength = 140

[menu]
  [[menu.main]]
    identifier = "categories"
    name = "カテゴリ"
    url = "/categories/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "タグ"
    url = "/tags/"
    weight = 20

#  customJS = ["js/copy.js"]
#  copyCode = true
#  customCSS = ["css/custom.css"]

#[markup]
#  [markup.highlight]
#    noClasses = false

#[languages]
#  [languages.ja]
#    languageName = "日本語"
#    weight = 1
#  [languages.en]
#    languageName = "English"
#    weight = 2
